name: ❓ Question
description: Ask a question about the project
title: '[QUESTION] '
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question!
        
        **Please check the documentation and existing issues before asking a question.**
        
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: I have a question about...
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to achieve
      placeholder: I'm trying to...
    validations:
      required: false
      
  - type: textarea
    id: attempted
    attributes:
      label: What I've Tried
      description: What have you already tried to solve this?
      placeholder: I have tried...
    validations:
      required: false
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details (if relevant)
      placeholder: |
        - OS: [e.g. Windows 10, macOS 12.0, Ubuntu 20.04]
        - Version: [e.g. 1.0.0]
        - Node.js: [e.g. 18.0.0]
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched for existing questions
          required: true 